hunter_config(
  gRPC
  VERSION
  1.34.0-p0
  CMAKE_ARGS
  gRPC_BUILD_TESTS=OFF
  gRPC_BUILD_CSHARP_EXT=OFF
  gRPC_BACKWARDS_COMPATIBILITY_MODE=OFF
  gRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF
  gRPC_BUILD_GRPC_NODE_PLUGIN=OFF
  gRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF
  gRPC_BUILD_GRPC_PHP_PLUGIN=OFF
  gRPC_BUILD_GRPC_PYTHON_PLUGIN=OFF
  gRPC_BUILD_GRPC_RUBY_PLUGIN=OFF
  CMAKE_C_FLAGS=-ffunction-sections\ -fdata-sections)
